Repository MariaMa-GitHub/Hungreat, pull requests merged in 2023-12, with the labels that each got.

#39 Analysis recipe
  src/entity/Recipe.java
  src/interface_adapter/analysis/AnalysisController.java
  src/interface_adapter/analysis/AnalysisPresenter.java
  src/use_case/analysis/AnalysisInputBoundary.java
  src/use_case/analysis/AnalysisInputData.java
  src/use_case/analysis/AnalysisInteractor.java
  src/use_case/analysis/AnalysisOutputBoundary.java
  src/use_case/analysis/AnalysisOutputData.java
Labels: enhancement

#40 SaveDAO Updated
  .gitignore
  SaveGoal.md
  src/app/Main.java
  src/data_access/RecipeDataAccessObject.java
  src/data_access/SavedRecipeDataAccessObject.java
  src/data_access/TemporaryRecipeDataAccessObject.java
  src/entity/Recipe.java
  src/interface_adapter/save/SaveController.java
  src/interface_adapter/save/SavePresenter.java
  src/use_case/save/SaveDataAccessInterface.java
  src/use_case/save/SaveInputBoundary.java
  src/use_case/save/SaveInputData.java
  src/use_case/save/SaveInteractor.java
  src/use_case/save/SaveOutputBoundary.java
  src/use_case/save/SaveOutputData.java
  src/view/SaveView.java
Labels: new feature

#44 Fixed and syntax error in nutrition to strings.
  src/entity/Recipe.java
Labels: enhancement

#51 Implemented the Create Use Case
  src/app/CreateUseCaseFactory.java
  src/app/Main.java
  src/app/SaveUseCaseFactory.java
  src/data_access/RecipeDataAccessObject.java
  src/data_access/SavedRecipeDataAccessObject.java
  src/entity/Recipe.java
  src/entity/RecipeFactory.java
  src/entity/RecipeInfo.java
  src/entity/RecipeInfoFactory.java
  src/interface_adapter/SaveViewModel.java
  src/interface_adapter/create/CreateController.java
  src/interface_adapter/create/CreatePresenter.java
  src/interface_adapter/create/CreateState.java
  src/interface_adapter/create/CreateViewModel.java
  src/interface_adapter/save/SaveController.java
  src/interface_adapter/save/SavePresenter.java
  src/use_case/TemporaryRecipeDataAccessInterface.java
  src/use_case/create/CreateDataAccessInterface.java
  src/use_case/create/CreateInputData.java
  src/use_case/create/CreateInteractor.java
  src/use_case/create/CreateOutputData.java
  src/use_case/save/SaveDataAccessInterface.java
  src/use_case/save/SaveInputBoundary.java
  src/use_case/save/SaveInputData.java
  src/use_case/save/SaveInteractor.java
  src/use_case/save/SaveOutputBoundary.java
  src/use_case/save/SaveOutputData.java
  src/view/CreateView.java
  src/view/SaveView.java
Labels: new feature

#52 Display recipe test
  pom.xml
  src/data_access/RecipeDataAccessObject.java
  src/entity/Recipe.java
  src/entity/RecipeInfo.java
  src/use_case/display/DisplayInteractor.java
  test/interface_adapter/DisplayControllerTest.java
  test/interface_adapter/DisplayPresenterTest.java
  test/interface_adapter/recommend/RecommendControllerTest.java
  test/interface_adapter/recommend/RecommendPresenterTest.java
  test/use_case/display/DisplayInteractorTest.java
  test/use_case/recommend/RecommendInteractorTest.java
Labels: enhancement

#57 Delete Hungreat.iml
  Hungreat.iml
Labels: invalid

#58 Delete SavedRecipes.txt
  SavedRecipes.txt
Labels: invalid

#61 Delete SaveGoal.md
  SaveGoal.md
Labels: invalid

#63 Fix save bug
  src/view/HomeView.java
  test/view/BrowseRecipesTest.java
Labels: bug

#65 Added dropdown lists for inputs
  src/app/Main.java
  src/view/BrowseView.java
  src/view/HomeView.java
  src/view/RecommendView.java
Labels: new feature

#68 Create Test Cases
  src/app/CreateUseCaseFactory.java
  src/interface_adapter/create/CreatePresenter.java
  test/interface_adapter/create/CreateControllerTest.java
  test/interface_adapter/create/CreatePresenterTest.java
  test/use_case/create/CreateInteractorTest.java
Labels: Testing

#70 Successfully update the FailView
  src/interface_adapter/save/SaveController.java
  src/interface_adapter/save/SavePresenter.java
  src/use_case/save/SaveInteractor.java
  src/view/HomeView.java
  src/view/SaveView.java
Labels: enhancement

#73 Finish writing save test
  src/app/RecommendUseCaseFactory.java
  src/use_case/recommend/RecommendInteractor.java
  test/interface_adapter/display/DisplayControllerTest.java
  test/interface_adapter/display/DisplayPresenterTest.java
  test/interface_adapter/save/SaveControllerTest.java
  test/interface_adapter/save/SavePresenterTest.java
  test/use_case/save/SaveInteractorTest.java
  test/view/BrowseRecipesTest.java
Labels: Testing

#77 Delete Interactor Test
  src/use_case/delete/DeleteInteractor.java
  test/use_case/delete/DeleteInteractorTest.java
  test/use_case/getSimilarRecipes/GetSimilarRecipeInteractorTest.java
Labels: Testing
